POST {{gateway_host}}/content/course/list?pageNo=1&pageSize=2
Content-Type: application/json

{
  "auditStatus": "202004",
  "courseName": "java",
  "publishStatus": ""
}
###
GET {{content_host}}/content/course-category/tree-nodes


### 创建课程
POST {{content_host}}/content/course
Content-Type: application/json


### course query
GET {{content_host}}/content/course/40
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ6aGFuZ3NhbiIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE2OTQzMzgwODAsImF1dGhvcml0aWVzIjpbInAxIl0sImp0aSI6ImI2ODJiYWQzLWFiMmQtNGMyNy1iNmIwLWUyYTM2ZDg4YWQxNCIsImNsaWVudF9pZCI6IlhjV2ViQXBwIn0.6hXBubqfHOyvAaLASYDSBnHWbggW8PyMcZcgWKLgxD0


### teach plan query
GET {{content_host}}/content/teachplan/117/tree-nodes

Java
### 删除课程计划
DELETE {{content_host}}/content/teachplan/245

### course query by gateway
GET {{gateway_host}}/content/course/40
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ6aGFuZ3NhbiIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE2OTQzMzgwODAsImF1dGhvcml0aWVzIjpbInAxIl0sImp0aSI6ImI2ODJiYWQzLWFiMmQtNGMyNy1iNmIwLWUyYTM2ZDg4YWQxNCIsImNsaWVudF9pZCI6IlhjV2ViQXBwIn0.6hXBubqfHOyvAaLASYDSBnHWbggW8PyMcZcgWKLgxD0
